/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwipeRouteImport } from './routes/swipe'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesThisOrThatRouteImport } from './routes/games.this-or-that'
import { Route as GamesStorageBudgetRouteImport } from './routes/games.storage-budget'
import { Route as GamesSpeedRoundRouteImport } from './routes/games.speed-round'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwipeRoute = SwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesThisOrThatRoute = GamesThisOrThatRouteImport.update({
  id: '/this-or-that',
  path: '/this-or-that',
  getParentRoute: () => GamesRoute,
} as any)
const GamesStorageBudgetRoute = GamesStorageBudgetRouteImport.update({
  id: '/storage-budget',
  path: '/storage-budget',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSpeedRoundRoute = GamesSpeedRoundRouteImport.update({
  id: '/speed-round',
  path: '/speed-round',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/swipe': typeof SwipeRoute
  '/terms': typeof TermsRoute
  '/games/speed-round': typeof GamesSpeedRoundRoute
  '/games/storage-budget': typeof GamesStorageBudgetRoute
  '/games/this-or-that': typeof GamesThisOrThatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/swipe': typeof SwipeRoute
  '/terms': typeof TermsRoute
  '/games/speed-round': typeof GamesSpeedRoundRoute
  '/games/storage-budget': typeof GamesStorageBudgetRoute
  '/games/this-or-that': typeof GamesThisOrThatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/memory': typeof MemoryRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/swipe': typeof SwipeRoute
  '/terms': typeof TermsRoute
  '/games/speed-round': typeof GamesSpeedRoundRoute
  '/games/storage-budget': typeof GamesStorageBudgetRoute
  '/games/this-or-that': typeof GamesThisOrThatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/memory'
    | '/privacy'
    | '/profile'
    | '/stats'
    | '/swipe'
    | '/terms'
    | '/games/speed-round'
    | '/games/storage-budget'
    | '/games/this-or-that'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/memory'
    | '/privacy'
    | '/profile'
    | '/stats'
    | '/swipe'
    | '/terms'
    | '/games/speed-round'
    | '/games/storage-budget'
    | '/games/this-or-that'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/memory'
    | '/privacy'
    | '/profile'
    | '/stats'
    | '/swipe'
    | '/terms'
    | '/games/speed-round'
    | '/games/storage-budget'
    | '/games/this-or-that'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  StatsRoute: typeof StatsRoute
  SwipeRoute: typeof SwipeRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swipe': {
      id: '/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof SwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/this-or-that': {
      id: '/games/this-or-that'
      path: '/this-or-that'
      fullPath: '/games/this-or-that'
      preLoaderRoute: typeof GamesThisOrThatRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/storage-budget': {
      id: '/games/storage-budget'
      path: '/storage-budget'
      fullPath: '/games/storage-budget'
      preLoaderRoute: typeof GamesStorageBudgetRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/speed-round': {
      id: '/games/speed-round'
      path: '/speed-round'
      fullPath: '/games/speed-round'
      preLoaderRoute: typeof GamesSpeedRoundRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesSpeedRoundRoute: typeof GamesSpeedRoundRoute
  GamesStorageBudgetRoute: typeof GamesStorageBudgetRoute
  GamesThisOrThatRoute: typeof GamesThisOrThatRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesSpeedRoundRoute: GamesSpeedRoundRoute,
  GamesStorageBudgetRoute: GamesStorageBudgetRoute,
  GamesThisOrThatRoute: GamesThisOrThatRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRouteWithChildren,
  MemoryRoute: MemoryRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  StatsRoute: StatsRoute,
  SwipeRoute: SwipeRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
